### ISSUE TITLE
Support symfony/event-dispatcher 4.3

### ISSUE THREAD

**Issue by stephanvierkant** [remotelyliving/php-dns#12]
Why is symfony/event-dispatcher 4.3 not supported?

**Comment by remotelyliving** [comment]
There's a change in 4.3 that adds warnings for calling the dispatcher's deprecated methods. Unfortunately I have a client that cannot upgrade so easily and are stuck on a v3 of event dispatcher. I haven't felt the need to release a BC / major update here unless there's a compelling reason.

**Comment by remotelyliving** [comment]
@stephanvierkant let me know if that answers you question and or there's anything else you'd like to discuss. Thanks!

**Comment by stephanvierkant** [comment]
Sorry, I don't understand what's the problem? What client and what warning(s) about deprecated methods? And why can't the usage of those methods not be changed/replaced? At some point we should support 4.3.
