### ISSUE TITLE
Update spatie/dns version

### ISSUE THREAD

**Issue by yerke** [remotelyliving/php-dns#38]
**Describe the bug**
Hello. Thanks for working on this package.
I am hitting https://github.com/spatie/dns/issues/49 . This issue is already solved in v1.5.0, whereas in php-dns spatie/dns is constrained with ^1.4. Can you please update to at least 1.5.0? Thanks.

**To Reproduce**
```
$resolver = new Dig();
$result = $resolver->getMXRecords('xn--merkat-1xa.com');
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by remotelyliving** [comment]
Thanks for the detailed report. Should be addressed in: https://github.com/remotelyliving/php-dns/pull/40

I am nuking the lockfile as this library should always be compatible with minor and patch releases of the required dependencies

**Comment by remotelyliving** [comment]
Should be fixed here: https://github.com/remotelyliving/php-dns/releases/tag/4.2
