### ISSUE TITLE
Update psr/cache and psr/log

### ISSUE THREAD

**Issue by stephanvierkant** [remotelyliving/php-dns#39]
I'd like to create a PR to allow the newest versions of psr/log and psr/cache. Would such a PR be merged?

**Comment by remotelyliving** [comment]
Actually, sorry, I didn't see this for a few days. I owe you one. Should be addressed in: https://github.com/remotelyliving/php-dns/pull/40

I am nuking the lockfile as this library should always be compatible with minor and patch releases of the required dependencies

**Comment by remotelyliving** [comment]
I feel so silly. I had no idea we'd had that many major releases! Helps to actually look doesn't in ;-) let me update and see if anything breaks. I'll push another release.

**Comment by remotelyliving** [comment]
@stephanvierkant thanks for adding this, I'll see why CI is broken but it seems unrelated to your changes.
