### ISSUE TITLE
Ability to use this in Symfony 6 (and Laravel 9)

### ISSUE THREAD

**Issue by dvdheiden** [remotelyliving/php-dns#47]
**Is your feature request related to a problem? Please describe.**
This package is currently not usable in Symfony 6 (or Laravel 9). The spatie/dns 1.x version range requires symfony/process version 5.x. Therefor you won't be able to install this in Symfony 6.

**Describe the solution you'd like**
We need to upgrade the spatie/dns dependency to at least version 2, which has some breaking changes to the 1.x range. Of course I'm willing to help, but before I put some time and effort into this, I would like to discuss this first.

**Describe alternatives you've considered**
I've not considered any alternative.

**Additional context**
When upgrading to spatie/dns version 2, PHP 8 will become the minimum required version of this package. I would like to know if that's acceptable for you.

**Comment by remotelyliving** [comment]
Really sorry about this as the issue email seems to have gone straight to hell in my inbox. I'm more than happy to do this in the next few days.

I've been meaning to upgrade this library to PHP8 for a while and might as well bring the rest of it into the future. I'll tag you on the PR. Thanks for raising this issue!

**Comment by remotelyliving** [comment]
@dvdheiden let me know if this fixes your issue: https://github.com/remotelyliving/php-dns/releases/tag/5.0.0 and thank you for your patience!

**Comment by dvdheiden** [comment]
I will check and let you know!

**Comment by dvdheiden** [comment]
I can confirm this is working now! Thank you!
