### ISSUE TITLE
mandrill._domainkey.domain.com. is not a valid hostname

### ISSUE THREAD

**Issue by sahanh** [remotelyliving/php-dns#6]
Was trying to check the following format to verify a DKIM setup. The validation part of the RemotelyLiving\PHPDNS\Entities\Hostname invalidates the provided format. Any way to update the validation scheme to allow the above format?

**Comment by remotelyliving** [comment]
Hi @sahanh, sorry about that! This lib started off with strict hostname validation via the `filter_var` flags, but as we've seen in the wild, the looser the validation the better. Thanks for bringing this to my attention. Please find the fix in https://github.com/remotelyliving/php-dns/tree/3.0.9

**Comment by sahanh** [comment]
Great, thanks.
