### ISSUE TITLE
GoogleDNS: DNS type 46

### ISSUE THREAD

**Issue by stephanvierkant** [remotelyliving/php-dns#8]
When using GoogleDNS, I'm having this error:

> Notice: Undefined offset: 46

`\RemotelyLiving\PHPDNS\Entities\DNSRecordType::CODE_TYPE_MAP` hasn't got an `RRSIG` (int 46) type. Should this be added, or should we ignore 'unknown' types?

**Comment by remotelyliving** [comment]
Ahhh interesting, good find. I think we should ignore for now but definitely log it as an event for interested parties. I'll whip something up this morning and propose it.

**Comment by remotelyliving** [comment]
We should always feel free to add more types as they're needed. I tried to cover 80% of the use cases most people have, but it's definitely not comprehensive.

**Comment by remotelyliving** [comment]
@stephanvierkant Check out the pull request and if you like it I'll go ahead and merge and release a new patch. I'm always open to feedback / critique so please don't be shy! Thanks again for reporting this.

**Comment by chathurangat** [comment]
@remotelyliving  i am also getting the same issue with the library version ("remotelyliving/php-dns": "^3.0")  used for laravel.  have you pushed any updated version for the library to overcome the issue?


[2019-08-08 13:56:55] local.ERROR: Undefined offset: 46 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 46 at /var/www/onboarding/backend/vendor/remotelyliving/php-dns/src/Entities/DNSRecordType.php:78)

**Comment by remotelyliving** [comment]
@chathurangat sorry, I haven't pushed the update. We had a new baby and I've been unplugged for a bit. 

Anyways, what does your call look like? Are you trying to query RRSIG records directly? I have this PR out there but I want to make sure it actually addresses your issue too. Can you please provide a code snippet of the call site?

**Comment by chathurangat** [comment]
@remotelyliving  Congratulations for you and your family on the new baby.  i have sent you a private message with code segment and domain details. 
Thanks

**Comment by remotelyliving** [comment]
Thanks so much @chathurangat! I haven't gotten the message yet, but just to be sure could you try emailing me at christian.h.thomas@me.com ? Sorry for the inconvenience.

**Comment by chathurangat** [comment]
@remotelyliving  sure. no worries. I will send you right now.

**Comment by remotelyliving** [comment]
@chathurangat thank you so much for the detailed description! That was very helpful. I'm confident my PR can address the issue so if you update to https://github.com/remotelyliving/php-dns/releases/tag/3.0.10 you should be good to go. In the future, if you'd like to see support for that type of record, I'd be more than happy to add it. Thanks!

**Comment by chathurangat** [comment]
@remotelyliving Thanks for the hard work!  just upgraded to the latest version and it worked fine. You are the best !
